package controllers

import (
	"net/http"

	"forzashop/backend/config"
	"forzashop/backend/models"

	"github.com/gin-gonic/gin"
)

// GetAdminNotifications fetches notifications for the logged-in admin
func GetAdminNotifications(c *gin.Context) {
	user := c.MustGet("currentUser").(models.User)

	var notifications []models.NotificationLog
	// Only fetch notifications generated by NotifyAdmin (where Channel is "system" and UserID is this admin)
	if err := config.DB.Where("user_id = ? AND channel = ?", user.ID, "system").Order("created_at desc").Limit(20).Find(&notifications).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to fetch notifications"})
		return
	}

	var unreadCount int64
	config.DB.Model(&models.NotificationLog{}).Where("user_id = ? AND channel = ? AND is_read = ?", user.ID, "system", false).Count(&unreadCount)

	c.JSON(http.StatusOK, gin.H{
		"data":         notifications,
		"unread_count": unreadCount,
	})
}

// MarkAdminNotificationAsRead marks specific or all notifications as read for the current admin
func MarkAdminNotificationAsRead(c *gin.Context) {
	user := c.MustGet("currentUser").(models.User)
	id := c.Param("id")

	if id == "all" {
		config.DB.Model(&models.NotificationLog{}).Where("user_id = ? AND channel = ? AND is_read = ?", user.ID, "system", false).Update("is_read", true)
	} else {
		config.DB.Model(&models.NotificationLog{}).Where("id = ? AND user_id = ?", id, user.ID).Update("is_read", true)
	}

	c.JSON(http.StatusOK, gin.H{"message": "Notification updated"})
}
